# arxivの学問領域の指定
subject: 'cat:physics.* OR cat:cs.* OR cat:cond-mat.* OR cat:quant-ph.*'

# 検索キーワード
keywords:
        Kitaev: 1
        Majorana: 1
        spin liquid: 1
        magnetic susceptibility : 1
        spin : 1

# 通知の閾値
score_threshold: 0
